# Generated by Django 5.1.7 on 2025-04-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_taskassignment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taskassignment',
            table='TaskAssignment',
        ),
    ]
