# Generated by Django 5.1.7 on 2025-04-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_taskassignment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshotsmonitoring',
            name='ssm_img',
            field=models.TextField(),
        ),
    ]
